.github/workflows/pull-request.yml
README.md
examples/App.tsx

Cypress build action

---

cypress/integration/ansible.spec.js
examples/App.tsx
examples/Forms/AnsibleExample.tsx
examples/Forms/AnsibleForm.tsx
examples/components/Results.tsx
src/FormWizardMode.tsx

ansible cleanup

---

cypress/integration/ansible.spec.js
examples/Forms/Ansible.hbs
examples/Forms/AnsibleForm.tsx
package.json
src/FormWizardPage.tsx
src/FormWizardSection.tsx

ansible cleanup and testing

---

src/FormWizardMode.tsx
src/FormWizardSection.tsx
src/inputs/FormWizardHidden.tsx
src/inputs/FormWizardInput.ts
src/inputs/FormWizardInputLabel.tsx
src/inputs/FormWizardSelect.tsx
src/inputs/FormWizardTextInput.tsx

cleanup input common code

---

examples/Ansible/AnsibleForm.tsx
examples/Credentials/CredentialsForm.tsx
src/FormWizardMode.tsx
src/FormWizardPage.tsx
src/inputs/FormWizardTiles.tsx

optional use of handlebars

---

examples/Application/AppForm.tsx

Hide Deploymentwindow for argocd

---

package-lock.json
package.json
tsconfig.json
wizards/tsconfig.json

npm publish setup

---

src/FormWizard.tsx
wizards/Demo.tsx
wizards/ROSA/RosaWizard.tsx

rosa wizard

---

src/components/FormWizardIndented.tsx
src/inputs/FormWizardCheckbox.tsx
src/inputs/FormWizardRadio.tsx
wizards/ROSA/RosaWizard.tsx

spacing fixes

---

src/FormWizard.css
src/FormWizard.tsx
src/contexts/FormWizardContext.tsx
src/contexts/FormWizardValidationContext.tsx
src/inputs/FormWizardArrayInput.tsx
src/inputs/FormWizardInput.ts
src/inputs/FormWizardSelect.tsx
src/inputs/FormWizardSelector.tsx
wizards/Policy/PolicyWizard.tsx

wizard step validation

---

src/inputs/FormWizardInput.ts
src/inputs/FormWizardSelect.tsx

setter fixes

---

wizards/Application/AppForm.tsx
wizards/Application/applicationTemplates/argoApplicationSet/templateArgoGit.hbs
wizards/Application/applicationTemplates/argoApplicationSet/templateArgoHelm.hbs

Minor fix for validation and placements

---

cypress/integration/credentials.ts
wizards/Credentials/CredentialsWizard.tsx

https://github.com/patternfly-labs/react-form-wizard/issues/28

Proxy fields, Credentials

---

wizards/Application/ApplicationExample.tsx
wizards/Application/ApplicationWizard.tsx
wizards/Demo.tsx

Add ApplicationExample

---

src/inputs/Select.tsx
wizards/Application/ApplicationWizard.tsx
wizards/Application/applicationTemplates/subscription/Application.hbs

application new namespace support

---

wizards/Argo/ArgoExample.tsx
wizards/Argo/ArgoWizard.tsx
wizards/common/test-data.ts

argo cd placement work

---

wizards/common/resources/IPolicySet.tsx

Update PolicySet apiVersion to v1beta1

---

wizards/Demo.tsx
wizards/PolicyAutomation/PolicyAutomationExamples.tsx
wizards/PolicyAutomation/PolicyAutomationWizard.tsx
wizards/Routes.tsx

Related issue: https://github.com/patternfly-labs/react-form-wizard/issues/67

Fire PolicyAutomation jobs callback on edit mode

---

cypress/integration/create-policy-automation.spec.ts
cypress/integration/edit-policy-automation.spec.ts
wizards/Placement/PlacementSection.tsx
wizards/PolicyAutomation/PolicyAutomationWizard.tsx

Filter placement resources by selected namespace

---

wizards/Placement/PlacementSection.tsx

Related issue: https://github.com/stolostron/backlog/issues/20768

Fix existing placementrule apigroup

---

wizards/Policy/PolicyExamples.tsx
wizards/Policy/PolicyWizard.tsx

stolostron/backlog#20854
stolostron/backlog#20786
stolostron/backlog#20710
stolostron/backlog#20698

fix various issues with policy wizard

---

src/inputs/AsyncSelect.tsx
wizards/Argo/ArgoExamples.tsx
wizards/Argo/ArgoWizard.tsx
wizards/Placement/Placement.tsx
wizards/Placement/PlacementSection.tsx
wizards/Policy/PolicyWizard.tsx
wizards/Policy/specifications.ts

stolostron/backlog#20954
stolostron/backlog#17646
stolostron/backlog#20981
stolostron/backlog#20977
stolostron/backlog#20976

various fixes

---

src/index.ts
wizards/PolicySet/PolicySetWizard.tsx

expose wizard contexts

---

wizards/Argo/ArgoWizard.tsx
wizards/Policy/PolicyWizard.tsx
wizards/PolicyAutomation/PolicyAutomationWizard.tsx

Signed-off-by: John Swanke <jswanke@redhat.com>

yaml editor override

---

wizards/Placement/PlacementRule.tsx

placement rule clusterCondition spec to array

---

wizards/Argo/ArgoWizard.tsx
wizards/common/validation.ts

Regarding: https://github.com/stolostron/backlog/issues/21027

Using validateWeUrl

---

wizards/Argo/ArgoWizard.tsx

regarding: https://github.com/stolostron/backlog/issues/21025
Additions:
- Fetching branches when new URL is created.

Get branch on create new URL

---

src/Wizard.tsx
src/WizardPage.tsx

fix padding in wizard

---

src/inputs/AsyncSelect.tsx

Revert commit: setting options to null on async callback

---

src/inputs/AsyncSelect.tsx
src/inputs/Input.ts
wizards/Policy/PolicyWizard.tsx
wizards/common/validation.ts

add validation for policyName+namespace

---

wizards/PolicyAutomation/PolicyAutomationWizard.tsx

Related issue: https://github.com/stolostron/backlog/issues/21322

Include manual mode for policy automation wizard

---

src/components/FieldGroup.tsx
src/contexts/useRandomID.tsx
src/inputs/AsyncSelect.tsx
src/inputs/Input.ts
src/inputs/Radio.tsx

fix radio buttons and spacing

---

src/inputs/ArrayInput.tsx

https://github.com/stolostron/backlog/issues/21318

Handle dropdown close on selection

---

package-lock.json
package.json
src/Wizard.tsx
wizards/Policy/PolicyWizard.tsx

performance enhancement - fast clone

---

wizards/Argo/ArgoWizard.tsx
wizards/Placement/PlacementSection.tsx

regarding: https://github.com/stolostron/backlog/issues/21402

Added spec to default yaml

---

wizards/Policy/PolicyWizard.tsx

Related issue: https://github.com/stolostron/backlog/issues/20855

Add remediation item to use policy-template action

---

wizards/Argo/ArgoExamples.tsx
wizards/Argo/ArgoWizard.tsx
wizards/Placement/MatchExpression.tsx
wizards/Placement/Placement.tsx
wizards/Placement/PlacementExamples.tsx
wizards/Placement/PlacementSection.tsx
wizards/Placement/PlacementWizard.tsx
wizards/Policy/PolicyExamples.tsx
wizards/Policy/PolicyWizard.tsx
wizards/PolicySet/PolicySetExamples.tsx
wizards/PolicySet/PolicySetWizard.tsx
wizards/common/test-data.ts

https://github.com/stolostron/backlog/issues/21480
https://github.com/stolostron/backlog/issues/21581
https://github.com/stolostron/backlog/issues/21404

placement fixes

---

wizards/Policy/PolicyWizard.tsx

policy name validation

---

wizards/Argo/ArgoWizard.tsx

Signed-off-by: randybrunopiverger <rbrunopi@redhat.com
regarding: https://github.com/stolostron/backlog/issues/21486
>

Added delete resources policy sync defaults

---

wizards/Argo/ArgoWizard.tsx

Sync both appset and subscription

---

wizards/Argo/ArgoWizard.tsx
wizards/Placement/Placement.tsx

regarding: https://github.com/stolostron/backlog/issues/21636#event-6420456736, https://github.com/stolostron/backlog/issues/21581

Remove clusterset.metadata.namespace conditional logic

---

wizards/Argo/ArgoWizard.tsx

regarding: https://github.com/stolostron/backlog/issues/21473

logic fix for channel creation + async

---

src/inputs/Checkbox.tsx
wizards/PolicyAutomation/PolicyAutomationWizard.tsx

Related issue: https://github.com/stolostron/backlog/issues/21698

Fix PolicyAutomation page crash and annotation var type

---

wizards/Placement/PlacementSection.tsx

https://github.com/stolostron/backlog/issues/21749

fix showing of placement selector when editing

---

wizards/Argo/ArgoWizard.tsx
wizards/Credentials/CredentialsWizard.tsx
wizards/Placement/Placement.tsx
wizards/Placement/PlacementBinding.tsx
wizards/Placement/PlacementRule.tsx
wizards/Placement/PlacementSection.tsx
wizards/Policy/PolicyExamples.tsx
wizards/Policy/PolicyWizard.tsx
wizards/PolicySet/PolicySetWizard.tsx
wizards/common/validation.ts

https://github.com/stolostron/backlog/issues/21744
https://github.com/stolostron/backlog/issues/21749
https://github.com/stolostron/backlog/issues/21617

policy wizard fixes

---

wizards/Catalog.tsx
wizards/Cluster/Provider.tsx
wizards/Demo.tsx
wizards/Routes.tsx

new cluster catalog

---

wizards/Policy/PolicyWizard.tsx
wizards/common/validation.ts

revert policyname validation to 63 char combined length cap

---

wizards/Placement/PlacementSection.tsx

https://github.com/stolostron/backlog/issues/21825

fix placement validation

---

wizards/Policy/PolicyWizard.tsx

https://github.com/stolostron/backlog/issues/21901

fix policy placement warning if not placed by policy set

---

wizards/PolicyAutomation/PolicyAutomationExamples.tsx
wizards/PolicyAutomation/PolicyAutomationWizard.tsx
wizards/common/resources/IConfigMap.ts

Related issue: https://github.com/stolostron/backlog/issues/21828

Show operator error in policyAutomation wizard

---

wizards/common/resources/IConfigMap.ts

Update ConfigMap definition

---

wizards/Placement/PlacementSection.tsx

https://github.com/stolostron/backlog/issues/21914
https://github.com/stolostron/backlog/issues/21915
https://github.com/stolostron/backlog/issues/21749

fix editing policy placements

---

src/inputs/SingleSelect.tsx

https://github.com/stolostron/backlog/issues/21825

clear single select is selection is not in options

---

wizards/Argo/ArgoWizard.tsx

https://github.com/stolostron/backlog/issues/21621

Change sync policy description

---

cypress/integration/edit-policy-set.spec.ts
src/inputs/SingleSelect.tsx
wizards/Policy/PolicyWizard.tsx
wizards/PolicySet/PolicySetWizard.tsx

disable editing of name and namespace based on resource uid

---

wizards/Argo/ArgoWizard.tsx
wizards/Policy/PolicyWizard.tsx
wizards/PolicySet/PolicySetWizard.tsx
wizards/common/Grid.tsx
wizards/common/Sync.tsx

https://github.com/stolostron/backlog/issues/22216

fix sync of name when editing app set

---

wizards/Argo/ArgoWizard.tsx

https://github.com/stolostron/backlog/issues/22236

Exclude bkup for apps that are deployed by appset

---

wizards/Policy/PolicyWizard.tsx

Related issue: https://github.com/stolostron/backlog/issues/22263

Fix undefined checks in policy wizard

---

cypress/integration/edit-policy-set.spec.ts
wizards/Argo/ArgoExamples.tsx
wizards/PolicySet/PolicySetExamples.tsx
wizards/PolicySet/PolicySetWizard.tsx
wizards/common/test-data.ts

Related issue: https://github.com/stolostron/backlog/issues/22241

edit policy set show policy status

---

cypress/integration/credentials.spec.ts
cypress/integration/input.spec.ts
src/components/LabelHelp.tsx
src/inputs/Input.ts
wizards/PolicyAutomation/PolicyAutomationWizard.tsx

related issue: https://github.com/stolostron/backlog/issues/21322

add helperText to policy automation wizard schedule header

---

wizards/PolicySet/PolicySetWizard.tsx

Alert user to selected policies that are missing

---

wizards/Argo/ArgoWizard.tsx

- Remove the default test option 
- Fix https://github.com/stolostron/backlog/issues/22503

Fix-argo-branches

---

wizards/Policy/PolicyExamples.tsx
wizards/Policy/PolicyWizard.tsx
wizards/common/test-data.ts

https://github.com/stolostron/backlog/issues/22523

make policy template names unique

---

wizards/Placement/PlacementSection.tsx
wizards/PolicySet/PolicySetWizard.tsx

add spec for clustercondition of managedcluster

---

wizards/PolicyAutomation/PolicyAutomationWizard.tsx

https://github.com/stolostron/backlog/issues/13951

String Change for Ansible operator alert link

---

src/inputs/WizTextArea.tsx
wizards/Demo.tsx
wizards/Hypershift/AmazonHypershiftWizard.tsx

Signed-off-by: James Talton <jtalton@redhat.com
>

hypershift-2

---

.github/workflows/pull-request.yml
package.json
wizards/Placement/MatchExpression.tsx
wizards/Policy/PolicyWizard.tsx

Addresses:
- https://github.com/stolostron/backlog/issues/23524

Add label selector to Policy Wizard

---

cypress/integration/input.spec.ts
src/inputs/WizTextArea.tsx
src/inputs/WizTextDetail.tsx
src/inputs/WizTextInput.tsx

Hide secrets for text area if intial value
Show secrets on clear text area so text can be entered

Hide secrets in Review step

---

cypress/integration/input.spec.ts
src/Section.tsx
src/components/HelperText.tsx
src/components/LabelHelp.tsx
src/inputs/Input.ts
src/inputs/WizArrayInput.tsx
src/inputs/WizCheckbox.tsx
src/inputs/WizKeyValue.tsx
src/inputs/WizRadio.tsx
src/inputs/WizSwitch.tsx
src/inputs/WizTimeRange.tsx
wizards/Inputs/InputsWizard.tsx

Allow ReactNode content for helperText
Add testing for WizSwitch

Commonize helperText code

---

cypress/integration/create-policy-set.spec.ts
wizards/Placement/PlacementSection.tsx
wizards/Policy/PolicyWizard.tsx
wizards/PolicySet/PolicySetWizard.tsx

For: https://github.com/stolostron/backlog/issues/24029

Config policy prune feature

---

cypress/integration/edit-policy-automation.spec.ts
wizards/PolicyAutomation/PolicyAutomationWizard.tsx
wizards/common/resources/IPolicyAutomation.ts

Signed-off-by: Chunxi Luo chuluo@redhat.com
https://github.com/stolostron/backlog/issues/23846

Add-GRC-Ansible-Automation-everyEvent-mode-on-UI

---

wizards/Policy/stable/SC-System-and-Communications-Protection/policy-limitmemory.yaml

Signed-off-by: Chunxi Luo chuluo@redhat.com
https://github.com/patternfly-labs/react-form-wizard/pull/154
fix for Console UI 2.5

Update complianceType for limit range policy

---

src/inputs/WizNumberInput.tsx
wizards/PolicyAutomation/PolicyAutomationWizard.tsx

Signed-off-by: Chunxi Luo chuluo@redhat.com
https://github.com/stolostron/backlog/issues/24697

Value of delayAfterRunSeconds is not shown on the final submit panel

---

src/Section.tsx

update section description type to ReactNode

---

.github/workflows/npm-publish.yml

[v1.8.z] Auto publish a minor update on any change

---

.github/workflows/npm-publish.yml

Automatically publish a minor update on changes to src

---

.github/workflows/npm-publish.yml

[v1.7.z] Auto publish a minor update on any change

---

src/inputs/WizKeyValue.tsx

ref: https://issues.redhat.com/browse/ACM-1997

Set key/value array to empty when input is empty

---

.github/workflows/npm-publish.yml

Limit z-stream npm updates to patch; tag with branch name

---

src/contexts/StringContext.tsx
src/inputs/WizTableSelect.tsx

related issue: https://issues.redhat.com/browse/ACM-3457
Add translations for WizTableSelect

Trans wiztableselect

---

src/inputs/WizArrayInput.tsx
src/inputs/WizKeyValue.tsx
src/inputs/WizStringsInput.tsx
wizards/Application/ApplicationWizard.tsx

Related to https://issues.redhat.com/browse/ACM-3122

Use PlusCircleIcon instead of PlusIcon

---

src/inputs/WizSelect.tsx
wizards/Argo/ArgoExamples.tsx
wizards/Argo/ArgoWizard.tsx

https://issues.redhat.com/browse/ACM-4483

Fix description for select options

---

src/inputs/WizArrayInput.tsx
wizards/Placement/Placement.tsx

Allow defaultRender

---

package-lock.json
src/Step.tsx

See: https://issues.redhat.com/browse/ACM-15271

ACM-15271 - Suppress implicit form submission

---

src/inputs/Input.ts
src/inputs/WizStringsInput.tsx

Regarding: https://issues.redhat.com/browse/ACM-17810

ACM-17810: Return props from useInput, use required prop in WizStringInput
